const STORAGE_KEY='ezee_vision_phase8';
const VERSION=8;
const DEFAULT_DB={schemaVersion:VERSION,user:null,settings:{academy:'EZEE VISION CHAMPUA',address:'Champua, Odisha',phone:'',signature:'Shahid Sir',dateFormat:'DD/MM/YYYY'},students:[{id:'EV001',name:'Rahul Kumar',cls:'Class 10',batch:'Batch A',phone:'',parent:'',address:'',dob:'',admissionDate:'',gender:'',active:true,feePlan:2000,due:1000,att:92},{id:'EV002',name:'Aman Kumar',cls:'Class 10',batch:'Batch B',phone:'',parent:'',address:'',dob:'',admissionDate:'',gender:'',active:true,feePlan:2000,due:0,att:88},{id:'EV003',name:'Priya Singh',cls:'Class 9',batch:'Batch A',phone:'',parent:'',address:'',dob:'',admissionDate:'',gender:'',active:true,feePlan:1800,due:2000,att:95}],batches:[{id:'B001',name:'Batch A',subject:'All Subjects',timing:'4:00 PM',days:'Mon-Wed-Fri',fee:2000},{id:'B002',name:'Batch B',subject:'Maths',timing:'5:00 PM',days:'Tue-Thu-Sat',fee:2000},{id:'B003',name:'Batch C',subject:'Science',timing:'6:00 PM',days:'Mon-Wed-Fri',fee:1800}],attendance:{},payments:[],income:[],expenses:[],incomeHeads:['Tuition Fees','Admission','Other Income'],expenseHeads:['Rent','Electricity','Salary','Stationery','Other'],exams:[],marks:[],enquiries:[],enquiryConversations:[],staff:[],staffAttendance:{},salary:[],todo:[],notifications:['Welcome to EZEE VISION CHAMPUA'],broadcasts:[],onlineExams:[],messages:[],qrLogs:[],families:[],discontinued:[],academyImages:[],motivationalPosts:[]};
let db=clone(DEFAULT_DB),activeStorageKey=STORAGE_KEY,cloudTimer=null,cloudQueue=Promise.resolve();
let state={page:'dashboard',selectedStudent:null,studentQuery:'',studentFilter:'all',attendanceBatch:'all',reportType:'students',editing:null};
const TITLES={dashboard:'Dashboard',students:'Students',attendance:'Attendance',fees:'Fees',more:'More',profile:'Student Profile',addStudent:'Register Student',notifications:'Notifications',batches:'Batch Management',exams:'Exams & Tests',performance:'Student Performance',income:'Income',expenses:'Expenses',enquiries:'Enquiry Manager',staff:'Staff Manager',reports:'Reports Center',settings:'Settings',backup:'Backup & Restore',todo:'To-Do Tasks',online:'Online Exams',messages:'Broadcast & Messages',motivational:'Motivational Posts',qr:'QR Attendance'};
function clone(v){return JSON.parse(JSON.stringify(v))}
function merge(base,saved){if(!saved||typeof saved!=='object')return base;Object.keys(saved).forEach(k=>{if(saved[k]&&typeof saved[k]==='object'&&!Array.isArray(saved[k])&&base[k]&&typeof base[k]==='object'&&!Array.isArray(base[k]))base[k]=merge(base[k],saved[k]);else base[k]=saved[k]});return base}
function normalize(v){const x=merge(clone(DEFAULT_DB),v||{});x.schemaVersion=VERSION;Object.keys(DEFAULT_DB).forEach(k=>{if(k==='settings'||k==='user')return;if(Array.isArray(DEFAULT_DB[k])&&!Array.isArray(x[k]))x[k]=[]});return x}
function loadLocal(){try{const r=localStorage.getItem(activeStorageKey);return normalize(r?JSON.parse(r):{})}catch(e){return clone(DEFAULT_DB)}}
function persist(){try{localStorage.setItem(activeStorageKey,JSON.stringify(db))}catch(e){console.warn(e)}}
function save(msg='',immediate=false){persist();const f=window.EVFirebase;if(!f?.configured||!f.auth?.currentUser)return;clearTimeout(cloudTimer);if(immediate)return void cloudNow(msg);cloudTimer=setTimeout(()=>cloudNow(msg),300)}
function cloudNow(msg=''){const f=window.EVFirebase,u=f?.auth?.currentUser;if(!f?.configured||!u)return;const snap=clone(db);cloudQueue=cloudQueue.then(async()=>{try{await f.saveCloud(u.uid,snap);if(msg)toast(msg)}catch(e){console.warn(e);if(msg)toast('Saved locally; cloud sync failed')}});return cloudQueue}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function money(v){return '₹'+Number(v||0).toLocaleString('en-IN')}
function dateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function monthKey(d=new Date()){return dateKey(d).slice(0,7)}
function dateText(){return new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function toast(m){const e=document.getElementById('toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2400)}
function go(p){state.page=p;render();window.scrollTo({top:0,behavior:'smooth'})}
function waitFirebase(){if(window.EVFirebase)return Promise.resolve();return new Promise(r=>window.addEventListener('ev-firebase-ready',r,{once:true}))}
async function init(){document.getElementById('pageDate').textContent=dateText();document.getElementById('loginForm').addEventListener('submit',login);document.getElementById('forgotBtn').addEventListener('click',forgot);document.getElementById('googleLoginBtn').addEventListener('click',google);document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));await waitFirebase();const f=window.EVFirebase;if(!f?.configured){toast('Firebase configuration missing');return}f.onAuthStateChanged(async u=>u?await authUser(u):showLogin())}
async function authUser(u){activeStorageKey=`${STORAGE_KEY}_${u.uid}`;db=loadLocal();db.user={uid:u.uid,name:u.displayName||db.user?.name||'Shahid Sir',login:u.email||'',role:db.user?.role||'Admin'};try{const c=await window.EVFirebase.loadCloud(u.uid);if(c){db=normalize(c);db.user={...db.user,uid:u.uid,login:u.email||db.user.login};persist()}else await cloudNow()}catch(e){console.warn(e)}showApp()}
function showApp(){document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');render()}
function showLogin(){activeStorageKey=STORAGE_KEY;document.getElementById('appView').classList.add('hidden');document.getElementById('loginView').classList.remove('hidden')}
function busy(v){const a=document.querySelector('#loginForm button[type=submit]'),g=document.getElementById('googleLoginBtn');if(a){a.disabled=v;a.textContent=v?'SIGNING IN…':'LOGIN'}if(g)g.disabled=v}
async function login(e){e.preventDefault();const email=loginId.value.trim(),pass=loginPassword.value;if(!email||!pass)return toast('Email and password required');busy(true);try{await window.EVFirebase.signIn(email,pass)}catch(x){toast(authErr(x));busy(false)}}
async function google(){busy(true);try{await window.EVFirebase.signInWithGoogle()}catch(x){toast(authErr(x));busy(false)}}
async function forgot(){const email=loginId.value.trim();if(!email)return toast('Enter your email first');try{await window.EVFirebase.resetPassword(email);toast('Reset email sent')}catch(x){toast(authErr(x))}}
function authErr(e){return ({'auth/invalid-credential':'Invalid email/password.','auth/unauthorized-domain':'Add your GitHub domain in Firebase Authorized domains.','auth/popup-blocked':'Allow popups for Google login.','auth/popup-closed-by-user':'Google login cancelled.','auth/network-request-failed':'Network error.'})[e?.code]||e?.message||'Login failed'}
async function logout(){try{await window.EVFirebase.signOut()}catch(e){}showLogin();toast('Logged out')}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));document.getElementById('pageTitle').textContent=TITLES[state.page]||'Dashboard';const pages={dashboard,students:studentsPage,attendance:attendancePage,fees:feesPage,more:morePage,profile:profilePage,addStudent:addStudentPage,notifications:notificationsPage,batches:batchesPage,exams:examsPage,performance:performancePage,income:incomePage,expenses:expensesPage,enquiries:enquiriesPage,staff:staffPage,reports:reportsPage,settings:settingsPage,backup:backupPage,todo:todoPage,online:onlinePage,messages:messagesPage,qr:qrPage,motivational:motivationalPage};document.getElementById('pageContent').innerHTML=(pages[state.page]||dashboard)()}
function stat(i,l,v){return `<div class="stat-card"><div class="stat-icon">${i}</div><div class="label">${l}</div><div class="value">${v}</div></div>`}
function action(i,l,p){return `<button class="action-btn" type="button" onclick="go('${p}')">${i} ${l}</button>`}
function dashboard(){const due=db.students.reduce((s,x)=>s+Number(x.due||0),0),today=attendanceSummary('all',dateKey()),income=monthTotal(db.income),expense=monthTotal(db.expenses),active=db.students.filter(x=>x.active!==false).length;return `<div class="hero-card"><h3>Good Morning, ${esc(db.user?.name||'Shahid Sir')} 👋</h3><p>${esc(db.settings.academy)} • Complete Coaching Management</p></div><div class="grid">${stat('👨‍🎓','Students',active)}${stat('🏫','Batches',db.batches.length)}${stat('✓','Today Present',today.present)}${stat('₹','Fees Due',money(due))}${stat('💰','Monthly Income',money(income))}${stat('💸','Monthly Expense',money(expense))}${stat('📈','Profit/Loss',money(income-expense))}${stat('📝','Exams',db.exams.length)}</div><div class="section-title"><h3>Quick Actions</h3></div><div class="quick-grid">${action('＋','Register Student','addStudent')}${action('✓','Take Attendance','attendance')}${action('₹','Collect Fees','fees')}${action('📝','Create Exam','exams')}${action('📊','Reports','reports')}</div><div class="section-title"><h3>Today's Attendance</h3><small>${dateText()}</small></div><div class="list-card"><div class="activity">🟢 Present <b>${today.present}</b></div><div class="activity">🔴 Absent <b>${today.absent}</b></div><div class="activity">📊 Percentage <b>${today.percent}%</b></div></div><div class="section-title"><h3>Recent Payments</h3></div><div class="list-card">${db.payments.slice(-5).reverse().map(p=>`<div class="activity">💰 ${esc(p.name)} paid ${money(p.amount)} <small>${esc(p.date)}</small></div>`).join('')||'<div class="activity">No payments yet.</div>'}</div>`}
function studentsPage(){const list=db.students.filter(s=>{const q=state.studentQuery.toLowerCase();return(!q||`${s.name} ${s.id} ${s.phone} ${s.parent} ${s.cls} ${s.batch}`.toLowerCase().includes(q))&&(state.studentFilter==='due'?Number(s.due)>0:state.studentFilter==='inactive'?s.active===false:true)});return `<div class="toolbar-row"><input class="search" value="${esc(state.studentQuery)}" placeholder="🔍 Search name, ID, mobile, batch" oninput="searchStudents(this.value)"></div><div class="filters"><button class="chip ${state.studentFilter==='all'?'active':''}" onclick="studentFilter('all')">All</button><button class="chip ${state.studentFilter==='due'?'active':''}" onclick="studentFilter('due')">Fees Due</button><button class="chip ${state.studentFilter==='inactive'?'active':''}" onclick="studentFilter('inactive')">Discontinued</button></div><div id="studentList">${studentCards(list)}</div><button class="primary-btn" onclick="go('addStudent')">＋ REGISTER NEW STUDENT</button>`}
function searchStudents(v){state.studentQuery=v;const e=document.getElementById('studentList');if(e){const list=db.students.filter(s=>`${s.name} ${s.id} ${s.phone} ${s.parent} ${s.cls} ${s.batch}`.toLowerCase().includes(v.toLowerCase()));e.innerHTML=studentCards(list)}}
function studentFilter(v){state.studentFilter=v;render()}
function studentCards(list){return list.map(s=>`<button class="student-card" onclick="openStudent('${esc(s.id)}')"><div class="avatar">${esc(initials(s.name))}</div><div class="student-main"><strong>${esc(s.name)}</strong><small>${esc(s.id)} • ${esc(s.cls)} • ${esc(s.batch)}</small></div><div class="student-meta">${attendancePercent(s.id)}%<br>${money(s.due)} due</div></button>`).join('')||'<div class="list-card empty">No students found.</div>'}
function initials(n){return String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function openStudent(id){state.selectedStudent=id;go('profile')}
function profilePage(){const s=db.students.find(x=>x.id===state.selectedStudent)||db.students[0];if(!s)return studentsPage();const pays=db.payments.filter(p=>p.studentId===s.id),att=studentAttendance(s.id),marks=db.marks.filter(m=>m.studentId===s.id);return `<button class="back-btn" onclick="go('students')">← Students</button><div class="panel"><div class="profile-head"><div class="avatar big">${esc(initials(s.name))}</div><div><h3>${esc(s.name)}</h3><div class="muted">${esc(s.id)} • ${esc(s.cls)} • ${esc(s.batch)}</div></div></div></div><div class="grid">${stat('✓','Attendance',att.percent+'%')}${stat('₹','Fees Due',money(s.due))}${stat('💳','Paid',money(pays.reduce((a,p)=>a+Number(p.amount||0),0)))}${stat('📝','Exams',marks.length)}</div><div class="panel"><h3>Student Details</h3>${kv('Parent',s.parent)}${kv('Mobile',s.phone)}${kv('DOB',s.dob)}${kv('Gender',s.gender)}${kv('Admission Date',s.admissionDate)}${kv('Address',s.address)}</div><div class="quick-grid">${action('₹','Collect Fee','fees')}${action('✓','Attendance','attendance')}${action('🪪','ID Card','reports')}${action('🎫','Registration Card','reports')}${action('📈','Performance','performance')}</div><div class="button-row"><button class="secondary-btn" onclick="callStudent('${esc(s.id)}')">📞 CALL</button><button class="secondary-btn" onclick="whatsappStudent('${esc(s.id)}')">💬 WHATSAPP</button></div><div class="button-row"><button class="secondary-btn" onclick="editStudent('${esc(s.id)}')">✏️ EDIT</button><button class="secondary-btn" onclick="toggleStudent('${esc(s.id)}')">${s.active===false?'RESTORE':'DISCONTINUE'}</button><button class="secondary-btn" onclick="printStudentCard('${esc(s.id)}')">🪪 PRINT ID CARD</button><button class="secondary-btn" onclick="printRegistration('${esc(s.id)}')">🎫 PRINT REGISTRATION</button><button class="danger" onclick="deleteStudent('${esc(s.id)}')">DELETE</button></div><div class="panel"><h3>Fee History</h3>${pays.map(p=>`<div class="activity">${esc(p.date)} • ${money(p.amount)} • ${esc(p.mode||'Cash')} <button class="chip" onclick="printReceipt('${esc(p.id)}')">Receipt</button></div>`).join('')||'<div class="muted">No payments.</div>'}</div>`}
function kv(a,b){return `<div class="kv"><span>${esc(a)}</span><b>${esc(b||'—')}</b></div>`}
function addStudentPage(){const s=state.editing?db.students.find(x=>x.id===state.editing):null;return `<button class="back-btn" onclick="go('students')">← Students</button><div class="panel"><h3>${s?'Edit':'Register New'} Student</h3><form onsubmit="submitStudent(event)"><input type="hidden" id="sid" value="${esc(s?.id||'')}"><label>Name</label><input class="field" id="sname" required value="${esc(s?.name||'')}"><label>Class</label><input class="field" id="sclass" required value="${esc(s?.cls||'')}"><label>Batch</label><select class="field" id="sbatch">${db.batches.map(b=>`<option value="${esc(b.name)}" ${(s?.batch||'')===b.name?'selected':''}>${esc(b.name)}</option>`).join('')}</select><label>Parent / Guardian</label><input class="field" id="sparent" value="${esc(s?.parent||'')}"><label>Mobile</label><input class="field" id="sphone" inputmode="tel" value="${esc(s?.phone||'')}"><label>DOB</label><input class="field" id="sdob" type="date" value="${esc(s?.dob||'')}"><label>Gender</label><select class="field" id="sgender"><option>Male</option><option>Female</option><option>Other</option></select><label>Admission Date</label><input class="field" id="sadmission" type="date" value="${esc(s?.admissionDate||dateKey())}"><label>Address</label><textarea class="field" id="saddress">${esc(s?.address||'')}</textarea><label>Monthly Fee</label><input class="field" id="sfee" type="number" min="0" value="${Number(s?.feePlan||0)}"><label>Opening Due</label><input class="field" id="sdue" type="number" min="0" value="${Number(s?.due||0)}"><button class="primary-btn" type="submit">${s?'UPDATE STUDENT':'SAVE STUDENT'}</button></form></div>`}
function submitStudent(e){e.preventDefault();const id=document.getElementById('sid').value,n={name:sname.value.trim(),cls:sclass.value.trim(),batch:sbatch.value,parent:sparent.value.trim(),phone:sphone.value.trim(),dob:sdob.value,gender:sgender.value,admissionDate:sadmission.value,address:saddress.value.trim(),feePlan:Number(sfee.value||0),due:Number(sdue.value||0),active:true};if(id){Object.assign(db.students.find(x=>x.id===id),n);toast('Student updated')}else{n.id=makeId('EV');n.att=100;db.students.push(n);toast('Student registered')}state.editing=null;save('',true);go('students')}
function makeId(p){return p+String(Date.now()).slice(-8)+Math.floor(Math.random()*9)}
function editStudent(id){state.editing=id;go('addStudent')}
function toggleStudent(id){const s=db.students.find(x=>x.id===id);if(!s)return;s.active=s.active===false;save('Student status updated');render()}
function deleteStudent(id){const s=db.students.find(x=>x.id===id);if(!s||!confirm(`Delete ${s.name}?`))return;db.students=db.students.filter(x=>x.id!==id);db.payments=db.payments.filter(x=>x.studentId!==id);db.marks=db.marks?.filter(x=>x.studentId!==id)||[];save('Student deleted',true);go('students')}
function batchesPage(){return `<button class="back-btn" onclick="go('more')">← More</button><div class="module-grid">${db.batches.map(b=>`<div class="module-card"><span class="ico">🏫</span><strong>${esc(b.name)}</strong><small>${esc(b.subject)} • ${esc(b.timing)}</small><small>${db.students.filter(s=>s.batch===b.name&&s.active!==false).length} students</small><button class="chip" onclick="batchReport('${esc(b.id)}')">Report</button><button class="chip" onclick="editBatch('${esc(b.id)}')">Edit</button><button class="chip" onclick="deleteBatch('${esc(b.id)}')">Delete</button></div>`).join('')}</div><button class="primary-btn" onclick="addBatch()">＋ ADD BATCH</button><button class="secondary-btn" onclick="promoteStudents()">⇧ PROMOTE STUDENTS</button>`}
function addBatch(){const name=prompt('Batch name');if(!name?.trim())return;if(db.batches.some(b=>b.name.toLowerCase()===name.trim().toLowerCase()))return toast('Batch already exists');const subject=prompt('Subject','All Subjects')||'',timing=prompt('Timing','4:00 PM')||'',days=prompt('Days','Mon-Wed-Fri')||'',fee=Number(prompt('Monthly fee','2000')||0);db.batches.push({id:makeId('B'),name:name.trim(),subject,timing,days,fee});save('Batch added');render()}
function editBatch(id){const b=db.batches.find(x=>x.id===id);if(!b)return;const n=prompt('Batch name',b.name);if(n===null)return;b.name=n.trim()||b.name;b.subject=prompt('Subject',b.subject)||b.subject;b.timing=prompt('Timing',b.timing)||b.timing;b.days=prompt('Days',b.days)||b.days;b.fee=Number(prompt('Monthly fee',b.fee)||b.fee);save('Batch updated');render()}
function deleteBatch(id){if(db.batches.length<=1)return toast('Keep at least one batch');const b=db.batches.find(x=>x.id===id);if(!b||!confirm(`Delete ${b.name}?`))return;db.batches=db.batches.filter(x=>x.id!==id);save('Batch deleted',true);render()}
function promoteStudents(){const old=prompt('Current batch');if(!old)return;const next=prompt('New batch');if(!next)return;let n=0;db.students.forEach(s=>{if(s.batch===old){s.batch=next;n++}});save(`${n} students promoted`,true);render()}
function attendanceSummary(batch,date){const ss=db.students.filter(s=>s.active!==false&&(batch==='all'||s.batch===batch));let p=0,a=0;ss.forEach(s=>{const v=db.attendance[`${date}_${s.id}`];if(v==='absent')a++;else if(v==='present')p++});const total=p+a;return{present:p,absent:a,percent:total?Math.round(p/total*100):0}}
function attendancePage(){const date=state.attDate||dateKey(),batch=state.attendanceBatch,ss=db.students.filter(s=>s.active!==false&&(batch==='all'||s.batch===batch)),sum=attendanceSummary(batch,date);return `<div class="panel"><label>Date</label><input class="field" type="date" value="${date}" onchange="setAttDate(this.value)"><label>Batch</label><select class="field" onchange="setAttBatch(this.value)"><option value="all">All Batches</option>${db.batches.map(b=>`<option ${batch===b.name?'selected':''}>${esc(b.name)}</option>`).join('')}</select></div><div class="grid">${stat('🟢','Present',sum.present)}${stat('🔴','Absent',sum.absent)}${stat('📊','Percentage',sum.percent+'%')}</div><div class="list-card attendance-list">${ss.map(s=>attRow(s,date)).join('')||'<div class="activity">No students.</div>'}</div><button class="primary-btn" onclick="markAll('present')">MARK ALL PRESENT</button><button class="secondary-btn" onclick="markAll('absent')">MARK ALL ABSENT</button><button class="secondary-btn" onclick="saveAttendanceNow()">☁️ SAVE ATTENDANCE</button><button class="secondary-btn" onclick="printAttendance()">🖨️ PRINT A4 ATTENDANCE</button>`}
function attRow(s,d){const v=db.attendance[`${d}_${s.id}`]||'';return `<div class="attendance-row"><div class="avatar">${esc(initials(s.name))}</div><div class="row-main"><strong>${esc(s.name)}</strong><small>${esc(s.batch)} • ${esc(s.cls)}</small></div><button class="toggle ${v==='present'?'present':''}" onclick="setAtt('${esc(s.id)}','${d}','present')">PRESENT</button><button class="toggle ${v==='absent'?'absent':''}" onclick="setAtt('${esc(s.id)}','${d}','absent')">ABSENT</button></div>`}
function setAtt(id,d,v){db.attendance[`${d}_${id}`]=v;persist();render();save()}
function setAttDate(v){state.attDate=v||dateKey();render()}
function setAttBatch(v){state.attendanceBatch=v;render()}
function markAll(v){const d=state.attDate||dateKey(),b=state.attendanceBatch;db.students.filter(s=>s.active!==false&&(b==='all'||s.batch===b)).forEach(s=>db.attendance[`${d}_${s.id}`]=v);save('Attendance updated');render()}
function saveAttendanceNow(){save('Attendance synced',true)}
function studentAttendance(id){const entries=Object.entries(db.attendance).filter(([k,v])=>k.endsWith('_'+id)&&v);let p=0,a=0;entries.forEach(([,v])=>v==='absent'?a++:p++);const t=p+a;return{percent:t?Math.round(p/t*100):0,present:p,absent:a,entries}}
function attendancePercent(id){return studentAttendance(id).percent}
function feesPage(){const due=db.students.reduce((a,s)=>a+Number(s.due||0),0),paid=monthTotal(db.payments.filter(p=>p.date?.startsWith(monthKey())),'amount');return `<div class="grid">${stat('₹','Pending Due',money(due))}${stat('💳','This Month',money(paid))}</div><div class="panel"><label>Student</label><select class="field" id="feeStudent">${db.students.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} — due ${money(s.due)}</option>`).join('')}</select><label>Amount</label><input class="field" id="feeAmount" type="number" min="1"><label>Payment Mode</label><select class="field" id="feeMode"><option>Cash</option><option>UPI</option><option>Bank Transfer</option><option>Cheque</option></select><label>Note</label><input class="field" id="feeNote"><button class="primary-btn" onclick="collectFee()">COLLECT FEE & SAVE</button></div><div class="panel"><h3>Pending Fees</h3>${db.students.filter(s=>Number(s.due)>0).map(s=>`<div class="activity activity-with-action"><span><b>${esc(s.name)}</b><br><small>${esc(s.batch)} • ${money(s.due)}</small></span><button class="chip" onclick="quickFee('${esc(s.id)}')">Collect</button><button class="chip" onclick="remindFee('${esc(s.id)}')">WhatsApp</button></div>`).join('')||'<div class="muted">No pending fees.</div>'}</div><div class="panel"><h3>Recent Payments</h3>${db.payments.slice(-15).reverse().map(p=>`<div class="activity activity-with-action"><span>${esc(p.date)} • ${esc(p.name)} • <b>${money(p.amount)}</b></span><button class="chip" onclick="printReceipt('${esc(p.id)}')">Receipt</button></div>`).join('')||'<div class="muted">No payments.</div>'}</div>`}
function collectFee(){const id=feeStudent.value,s=db.students.find(x=>x.id===id),amount=Number(feeAmount.value||0);if(!s||amount<=0)return toast('Enter valid fee');s.due=Math.max(0,Number(s.due||0)-amount);const p={id:makeId('PAY'),studentId:s.id,name:s.name,amount,date:dateKey(),mode:feeMode.value,note:feeNote.value.trim()};db.payments.push(p);save('Fee saved',true);render();setTimeout(()=>{if(confirm('Print receipt now?'))printReceipt(p.id)},50)}
function quickFee(id){state.page='fees';render();setTimeout(()=>{feeStudent.value=id;feeAmount.value=db.students.find(s=>s.id===id)?.due||0},0)}
function remindFee(id){const s=db.students.find(x=>x.id===id);if(!s?.phone)return toast('Student mobile not available');openWhatsApp(s.phone,`Dear Parent, fee reminder for ${s.name}. Pending amount: ${money(s.due)}. - ${db.settings.academy}`)}
function printReceipt(id){const p=db.payments.find(x=>x.id===id);const s=db.students.find(x=>x.id===p?.studentId);if(!p)return;printWindow('Fee Receipt',`<div class="receipt"><h2>${esc(db.settings.academy)}</h2><p>${esc(db.settings.address)}</p><hr><h3>FEE RECEIPT</h3>${kv('Receipt No',p.id)}${kv('Date',p.date)}${kv('Student',s?.name||p.name)}${kv('Batch',s?.batch||'')}${kv('Amount',money(p.amount))}${kv('Mode',p.mode)}${kv('Balance Due',money(s?.due||0))}<hr><p>Authorized Signature: ${esc(db.settings.signature)}</p></div>`)}
function incomePage(){return financePage('income','Income')}
function expensesPage(){return financePage('expenses','Expenses')}
function financePage(type,title){const arr=db[type],total=monthTotal(arr),heads=type==='income'?db.incomeHeads:db.expenseHeads;return `<div class="grid">${stat(type==='income'?'💰':'💸',`This Month ${title}`,money(total))}${stat('📒','Entries',arr.length)}</div><div class="panel"><h3>Add ${title}</h3><select class="field" id="fhead">${heads.map(h=>`<option>${esc(h)}</option>`).join('')}</select><input class="field" id="famount" type="number" min="0" placeholder="Amount"><input class="field" id="fdate" type="date" value="${dateKey()}"><input class="field" id="fnote" placeholder="Note"><button class="primary-btn" onclick="addFinance('${type}')">SAVE ${title.toUpperCase()}</button><button class="secondary-btn" onclick="addFinanceHead('${type}')">＋ ADD HEAD</button></div><div class="list-card">${arr.slice().reverse().map(x=>`<div class="activity activity-with-action"><span>${esc(x.date)} • ${esc(x.head)} • <b>${money(x.amount)}</b><br><small>${esc(x.note||'')}</small></span><button class="chip" onclick="deleteFinance('${type}','${esc(x.id)}')">Delete</button></div>`).join('')||'<div class="activity">No entries.</div>'}</div>`}
function addFinance(type){const amount=Number(famount.value||0);if(amount<=0)return toast('Enter amount');db[type].push({id:makeId(type==='income'?'IN':'EX'),head:fhead.value,amount,date:fdate.value||dateKey(),note:fnote.value.trim()});save('Entry saved');render()}
function addFinanceHead(type){const h=prompt('New head');if(!h?.trim())return;(type==='income'?db.incomeHeads:db.expenseHeads).push(h.trim());save('Head added');render()}
function deleteFinance(type,id){if(!confirm('Delete entry?'))return;db[type]=db[type].filter(x=>x.id!==id);save('Entry deleted');render()}
function monthTotal(arr,field='amount'){const m=monthKey();return arr.filter(x=>x.date?.startsWith(m)).reduce((a,x)=>a+Number(x[field]||0),0)}
function examsPage(){return `<div class="panel"><h3>Create Exam</h3><input class="field" id="ename" placeholder="Exam name"><input class="field" id="esub" placeholder="Subject"><select class="field" id="ebatch">${db.batches.map(b=>`<option>${esc(b.name)}</option>`).join('')}</select><input class="field" id="edate" type="date" value="${dateKey()}"><button class="primary-btn" onclick="createExam()">CREATE EXAM</button></div><div class="list-card">${db.exams.map(e=>`<div class="activity activity-with-action"><span><b>${esc(e.name)}</b><br><small>${esc(e.subject)} • ${esc(e.batch)} • ${esc(e.date)}</small></span><button class="chip" onclick="enterMarks('${esc(e.id)}')">Marks</button><button class="chip" onclick="printExamReport('${esc(e.id)}')">Report</button><button class="chip" onclick="deleteExam('${esc(e.id)}')">Delete</button></div>`).join('')||'<div class="activity">No exams.</div>'}</div>`}
function createExam(){if(!ename.value.trim())return toast('Exam name required');db.exams.push({id:makeId('EXM'),name:ename.value.trim(),subject:esub.value.trim(),batch:ebatch.value,date:edate.value||dateKey(),active:true});save('Exam created');render()}
function enterMarks(id){const e=db.exams.find(x=>x.id===id);if(!e)return;const ss=db.students.filter(s=>s.batch===e.batch&&s.active!==false);ss.forEach(s=>{let old=db.marks.find(m=>m.examId===id&&m.studentId===s.id);const v=prompt(`Marks for ${s.name} (0-100)`,old?.marks??'');if(v!==null&&v!==''){if(old)old.marks=Number(v);else db.marks.push({id:makeId('MRK'),examId:id,studentId:s.id,marks:Number(v),rating:''})}});save('Marks saved',true);render()}
function deleteExam(id){if(!confirm('Delete exam and marks?'))return;db.exams=db.exams.filter(x=>x.id!==id);db.marks=db.marks.filter(x=>x.examId!==id);save('Exam deleted',true);render()}
function performancePage(){const rows=db.students.map(s=>{const ms=db.marks.filter(m=>m.studentId===s.id);const avg=ms.length?Math.round(ms.reduce((a,m)=>a+Number(m.marks||0),0)/ms.length):0;return{s,avg}});return `<div class="panel"><h3>Performance Overview</h3>${rows.map(r=>`<div class="activity activity-with-action"><span><b>${esc(r.s.name)}</b><br><small>${r.avg}% average • ${r.s.active===false?'Discontinued':'Active'}</small></span><button class="chip" onclick="rateStudent('${esc(r.s.id)}')">Rate</button></div>`).join('')||'<div class="muted">No students.</div>'}</div>`}
function rateStudent(id){const s=db.students.find(x=>x.id===id),r=prompt(`Rating for ${s?.name}`,'Good');if(r===null)return;db.messages.push({id:makeId('RAT'),type:'rating',studentId:id,text:r,date:dateKey()});save('Rating saved')}
function enquiriesPage(){return `<div class="panel"><h3>Add Enquiry</h3><input class="field" id="qname" placeholder="Name"><input class="field" id="qphone" placeholder="Mobile"><input class="field" id="qcourse" placeholder="Course/Class"><input class="field" id="qfollow" type="date" value="${dateKey()}"><textarea class="field" id="qnote" placeholder="Notes"></textarea><button class="primary-btn" onclick="addEnquiry()">SAVE ENQUIRY</button></div><div class="list-card">${db.enquiries.map(q=>`<div class="activity activity-with-action"><span><b>${esc(q.name)}</b> • ${esc(q.phone)}<br><small>${esc(q.course)} • Follow-up ${esc(q.follow)} • ${esc(q.status)}</small></span><button class="chip" onclick="conversation('${esc(q.id)}')">Conversation</button><button class="chip" onclick="toggleEnquiry('${esc(q.id)}')">${q.status==='Open'?'Close':'Open'}</button><button class="chip" onclick="deleteEnquiry('${esc(q.id)}')">Delete</button></div>`).join('')||'<div class="activity">No enquiries.</div>'}</div>`}
function addEnquiry(){if(!qname.value.trim())return toast('Name required');db.enquiries.push({id:makeId('ENQ'),name:qname.value.trim(),phone:qphone.value.trim(),course:qcourse.value.trim(),follow:qfollow.value,status:'Open',note:qnote.value.trim()});save('Enquiry added');render()}
function toggleEnquiry(id){const q=db.enquiries.find(x=>x.id===id);if(!q)return;q.status=q.status==='Open'?'Closed':'Open';save('Status updated');render()}
function deleteEnquiry(id){if(!confirm('Delete enquiry?'))return;db.enquiries=db.enquiries.filter(x=>x.id!==id);save('Enquiry deleted');render()}
function conversation(id){const q=db.enquiries.find(x=>x.id===id),t=prompt(`Conversation with ${q?.name}`,'');if(!t?.trim())return;db.enquiryConversations.push({id:makeId('CON'),enquiryId:id,date:dateKey(),text:t.trim()});save('Conversation saved')}
function staffPage(){return `<div class="panel"><h3>Add Staff</h3><input class="field" id="stname" placeholder="Staff name"><input class="field" id="stphone" placeholder="Mobile"><input class="field" id="strole" placeholder="Role / Subject"><input class="field" id="stsalary" type="number" placeholder="Monthly salary"><button class="primary-btn" onclick="addStaff()">SAVE STAFF</button></div><div class="list-card">${db.staff.map(s=>`<div class="activity activity-with-action"><span><b>${esc(s.name)}</b><br><small>${esc(s.role)} • ${money(s.salary)}</small></span><button class="chip" onclick="staffAttendance('${esc(s.id)}')">Attendance</button><button class="chip" onclick="paySalary('${esc(s.id)}')">Salary</button><button class="chip" onclick="deleteStaff('${esc(s.id)}')">Delete</button></div>`).join('')||'<div class="activity">No staff.</div>'}</div>`}
function addStaff(){if(!stname.value.trim())return toast('Name required');db.staff.push({id:makeId('STF'),name:stname.value.trim(),phone:stphone.value.trim(),role:strole.value.trim(),salary:Number(stsalary.value||0),active:true});save('Staff added');render()}
function deleteStaff(id){if(!confirm('Delete staff?'))return;db.staff=db.staff.filter(x=>x.id!==id);save('Staff deleted');render()}
function staffAttendance(id){const v=prompt('Present or Absent','Present');if(!v)return;db.staffAttendance[`${dateKey()}_${id}`]=v;save('Staff attendance saved')}
function paySalary(id){const s=db.staff.find(x=>x.id===id);if(!s)return;const amount=Number(prompt(`Salary for ${s.name}`,s.salary)||0);if(!amount)return;db.salary.push({id:makeId('SAL'),staffId:id,name:s.name,amount,date:dateKey()});db.expenses.push({id:makeId('EX'),head:'Salary',amount,date:dateKey(),note:s.name});save('Salary recorded',true);render()}
function reportsPage(){const opts=[['students','👨‍🎓','Student List'],['student-card','🪪','Student ID Cards'],['registration','🎫','Registration Cards'],['attendance','✓','Attendance Report'],['fees','₹','Fees Collection'],['due','⚠️','Due Fees'],['payments','💳','Payment History'],['income','💰','Income Report'],['expense','💸','Expense Report'],['profit','📈','Profit / Loss'],['exams','📝','Exam Report'],['performance','🏆','Performance Report'],['batch','🏫','Batch Reports'],['enquiry','📩','Enquiry Report'],['staff','👨‍🏫','Staff Report'],['birthday','🎂','Birthday Alert'],['course','🎓','Course Completion']];return `<div class="panel"><h3>Giant Reports</h3><p class="muted">Every report can be exported and printed in A4 format.</p></div><div class="module-grid">${opts.map(o=>`<button class="module-card" onclick="generateReport('${o[0]}')"><span class="ico">${o[1]}</span><strong>${o[2]}</strong><small>Print • Excel • CSV</small></button>`).join('')}</div>`}
function reportRows(type){if(type==='students')return db.students.map(s=>({ID:s.id,Name:s.name,Class:s.cls,Batch:s.batch,Mobile:s.phone,Attendance:attendancePercent(s.id)+'%',Due:s.due}));if(type==='attendance')return Object.entries(db.attendance).map(([k,v])=>{const [d,id]=k.split('_');const s=db.students.find(x=>x.id===id);return{Date:d,Student:s?.name||id,Batch:s?.batch||'',Status:v}});if(type==='fees'||type==='due')return db.students.filter(s=>type==='fees'||Number(s.due)>0).map(s=>({ID:s.id,Name:s.name,Batch:s.batch,MonthlyFee:s.feePlan,Due:s.due}));if(type==='payments')return db.payments.map(p=>({Date:p.date,Receipt:p.id,Student:p.name,Amount:p.amount,Mode:p.mode}));if(type==='income')return db.income.map(x=>({Date:x.date,Head:x.head,Amount:x.amount,Note:x.note}));if(type==='expense')return db.expenses.map(x=>({Date:x.date,Head:x.head,Amount:x.amount,Note:x.note}));if(type==='profit')return [{Month:monthKey(),Income:monthTotal(db.income),Expense:monthTotal(db.expenses),Profit:monthTotal(db.income)-monthTotal(db.expenses)}];if(type==='exams')return db.marks.map(m=>{const e=db.exams.find(x=>x.id===m.examId),s=db.students.find(x=>x.id===m.studentId);return{Exam:e?.name||'',Student:s?.name||'',Batch:e?.batch||'',Marks:m.marks}});if(type==='performance')return db.students.map(s=>{const ms=db.marks.filter(m=>m.studentId===s.id);return{Student:s.name,Average:ms.length?Math.round(ms.reduce((a,m)=>a+Number(m.marks),0)/ms.length):0,Attendance:attendancePercent(s.id)}});if(type==='batch')return db.batches.map(b=>({Batch:b.name,Subject:b.subject,Timing:b.timing,Students:db.students.filter(s=>s.batch===b.name&&s.active!==false).length,Fee:b.fee}));if(type==='enquiry')return db.enquiries.map(q=>({Name:q.name,Mobile:q.phone,Course:q.course,Followup:q.follow,Status:q.status}));if(type==='staff')return db.staff.map(s=>({Name:s.name,Mobile:s.phone,Role:s.role,Salary:s.salary}));if(type==='birthday')return db.students.filter(s=>s.dob&&s.dob.slice(5)===dateKey().slice(5)).map(s=>({Name:s.name,DOB:s.dob,Mobile:s.phone,Batch:s.batch}));if(type==='course')return db.students.filter(s=>s.active===false).map(s=>({ID:s.id,Name:s.name,Batch:s.batch,Status:'Completed/Discontinued'}));return[]}
function generateReport(type){const rows=reportRows(type);const title=type.replace(/-/g,' ').toUpperCase()+' REPORT';if(!rows.length)return toast('No records for this report');const table=tableHtml(rows);printWindow(title,`<h2>${esc(db.settings.academy)}</h2>${table}<p>Generated: ${esc(dateText())}</p>`);exportExcel(rows,type+'-report.xls');}
function tableHtml(rows){const keys=Object.keys(rows[0]||{});return `<table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function exportExcel(rows,name){const html=`<html><head><meta charset="utf-8"></head><body><h2>${esc(db.settings.academy)}</h2>${tableHtml(rows)}</body></html>`;downloadFile(name,html,'application/vnd.ms-excel')}
function exportCsvRows(rows,name){if(!rows.length)return toast('No data');const keys=Object.keys(rows[0]),csv=[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(csvCell).join(',')).join('\n');downloadFile(name,csv,'text/csv;charset=utf-8')}
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
function printWindow(title,body){const w=window.open('','_blank','width=950,height=750');if(!w)return toast('Allow popups for printing');w.document.write(`<!doctype html><html><head><title>${esc(title)}</title><meta charset="utf-8"><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#111;font-size:12px}h1,h2,h3{margin:5px 0}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{border:1px solid #555;padding:6px}th{font-weight:700;background:#eee}.kv{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #ddd}.receipt{text-align:center}.receipt .kv{text-align:left}</style></head><body>${body}</body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print()},250)}
function printStudentCard(id){const s=db.students.find(x=>x.id===id);if(!s)return;printWindow('Student ID Card',`<div style="border:2px solid #0a3271;padding:25px;width:340px;margin:auto;text-align:center"><h2>${esc(db.settings.academy)}</h2><div style="font-size:45px;font-weight:bold;margin:20px">${esc(initials(s.name))}</div><h3>${esc(s.name)}</h3><p>ID: ${esc(s.id)}</p><p>${esc(s.cls)} • ${esc(s.batch)}</p><p>Mobile: ${esc(s.phone)}</p><p>${esc(db.settings.signature)}</p></div>`)}
function printRegistration(id){const s=db.students.find(x=>x.id===id);if(!s)return;printWindow('Registration Card',`<h2>${esc(db.settings.academy)} — STUDENT REGISTRATION CARD</h2>${tableHtml([s])}<p>Authorized Signature: ${esc(db.settings.signature)}</p>`)}
function printExamReport(id){const e=db.exams.find(x=>x.id===id);if(!e)return;const rows=db.marks.filter(m=>m.examId===id).map(m=>{const s=db.students.find(x=>x.id===m.studentId);return{Student:s?.name||'',Class:s?.cls||'',Marks:m.marks,Grade:grade(m.marks)}});if(rows.length)printWindow('Exam Report',`<h2>${esc(e.name)} • ${esc(e.subject)}</h2>${tableHtml(rows)}`);else toast('No marks entered')}
function grade(n){n=Number(n);return n>=90?'A+':n>=80?'A':n>=70?'B+':n>=60?'B':n>=50?'C':n>=40?'D':'F'}
function printAttendance(){const d=state.attDate||dateKey(),b=state.attendanceBatch,rows=db.students.filter(s=>s.active!==false&&(b==='all'||s.batch===b)).map(s=>({ID:s.id,Student:s.name,Batch:s.batch,Status:db.attendance[`${d}_${s.id}`]||'Not Marked'}));printWindow('Attendance Sheet',`<h2>${esc(db.settings.academy)} — ATTENDANCE SHEET</h2><p>Date: ${esc(d)} • Batch: ${esc(b)}</p>${tableHtml(rows)}`)}
function todoPage(){return `<div class="panel"><input class="field" id="todotext" placeholder="Task"><input class="field" id="tododate" type="date" value="${dateKey()}"><button class="primary-btn" onclick="addTodo()">ADD TASK</button></div><div class="list-card">${db.todo.map(t=>`<div class="activity activity-with-action"><span>${t.done?'✅':'⬜'} <b>${esc(t.text)}</b><br><small>${esc(t.date)}</small></span><button class="chip" onclick="toggleTodo('${esc(t.id)}')">${t.done?'Undo':'Done'}</button><button class="chip" onclick="deleteTodo('${esc(t.id)}')">Delete</button></div>`).join('')||'<div class="activity">No tasks.</div>'}</div>`}
function addTodo(){if(!todotext.value.trim())return;db.todo.push({id:makeId('TODO'),text:todotext.value.trim(),date:tododate.value,done:false});save('Task added');render()}
function toggleTodo(id){const t=db.todo.find(x=>x.id===id);if(t)t.done=!t.done;save('Task updated');render()}
function deleteTodo(id){db.todo=db.todo.filter(x=>x.id!==id);save('Task deleted');render()}
function onlinePage(){return `<div class="panel"><h3>Online MCQ Exam</h3><input class="field" id="oname" placeholder="Exam name"><input class="field" id="oduration" type="number" min="1" value="30" placeholder="Minutes"><select class="field" id="obatch">${db.batches.map(b=>`<option>${esc(b.name)}</option>`).join('')}</select><textarea class="field" id="oquestions" rows="7" placeholder="One MCQ per line: Question | A | B | C | D | Correct(A/B/C/D)"></textarea><button class="primary-btn" onclick="createOnlineExam()">CREATE ONLINE EXAM</button></div><div class="list-card">${db.onlineExams.map(e=>`<div class="activity activity-with-action"><span><b>${esc(e.name)}</b><br><small>${esc(e.batch)} • ${e.duration} min • ${e.active?'Active':'Inactive'} • ${e.questions.length} questions</small></span><button class="chip" onclick="toggleOnline('${esc(e.id)}')">${e.active?'Deactivate':'Activate'}</button><button class="chip" onclick="runOnline('${esc(e.id)}')">Take Test</button><button class="chip" onclick="deleteOnline('${esc(e.id)}')">Delete</button></div>`).join('')||'<div class="activity">No online exams.</div>'}</div>`}
function createOnlineExam(){if(!oname.value.trim())return toast('Exam name required');const qs=oquestions.value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const a=line.split('|').map(v=>v.trim());return{q:a[0],A:a[1],B:a[2],C:a[3],D:a[4],correct:(a[5]||'A').toUpperCase()}});if(!qs.length)return toast('Add at least one MCQ');db.onlineExams.push({id:makeId('ON'),name:oname.value.trim(),duration:Number(oduration.value||30),batch:obatch.value,questions:qs,active:true});save('Online exam created');render()}
function toggleOnline(id){const e=db.onlineExams.find(x=>x.id===id);if(e)e.active=!e.active;save('Exam status updated');render()}
function deleteOnline(id){if(!confirm('Delete online exam?'))return;db.onlineExams=db.onlineExams.filter(x=>x.id!==id);save('Online exam deleted');render()}
function runOnline(id){const e=db.onlineExams.find(x=>x.id===id);if(!e||!e.active)return toast('Exam is inactive');let score=0;for(const q of e.questions){const a=prompt(`${q.q}\nA) ${q.A}\nB) ${q.B}\nC) ${q.C}\nD) ${q.D}`,'A');if(a?.toUpperCase()===q.correct)score++}alert(`Result: ${score}/${e.questions.length}`);db.messages.push({id:makeId('RES'),type:'onlineResult',examId:id,score,total:e.questions.length,date:dateKey()});save('Result saved')}
function messagesPage(){return `<div class="panel"><h3>Broadcast / Messaging</h3><textarea class="field" id="msgtext" placeholder="Message to students/parents"></textarea><button class="primary-btn" onclick="broadcastAll()">BROADCAST TO ALL</button><button class="secondary-btn" onclick="sendSmsAll()">OPEN SMS TO ALL</button></div><div class="list-card">${db.messages.filter(x=>x.type==='broadcast').slice(-20).reverse().map(m=>`<div class="activity">${esc(m.date)} • ${esc(m.text)}</div>`).join('')||'<div class="activity">No broadcasts.</div>'}</div>`}
function broadcastAll(){const t=msgtext.value.trim();if(!t)return toast('Message required');db.broadcasts.push({id:makeId('BC'),text:t,date:dateKey()});db.messages.push({id:makeId('MSG'),type:'broadcast',text:t,date:dateKey()});save('Broadcast saved');render()}
function sendSmsAll(){const t=msgtext.value.trim();if(!t)return toast('Message required');const nums=db.students.map(s=>s.phone).filter(Boolean);if(!nums.length)return toast('No student mobiles');window.location.href=`sms:${nums[0]}?body=${encodeURIComponent(t)}`}
function qrPage(){return `<div class="panel"><h3>QR Attendance</h3><p class="muted">Use a student ID or phone number for fast attendance. Camera scanning is enabled where the browser supports BarcodeDetector.</p><input class="field" id="qrvalue" placeholder="Scan/type Student ID or mobile"><button class="primary-btn" onclick="qrMark()">MARK ATTENDANCE</button><button class="secondary-btn" onclick="cameraQR()">📷 CAMERA SCAN</button><div id="qrstatus"></div></div><div class="list-card">${db.qrLogs.slice(-10).reverse().map(x=>`<div class="activity">${esc(x.date)} • ${esc(x.name)} • ${esc(x.status)}</div>`).join('')||'<div class="activity">No QR logs.</div>'}</div>`}
function qrMark(){const v=qrvalue.value.trim().toLowerCase(),s=db.students.find(x=>x.id.toLowerCase()===v||x.phone===v||x.name.toLowerCase()===v);if(!s)return toast('Student not found');db.attendance[`${dateKey()}_${s.id}`]='present';db.qrLogs.push({id:makeId('QR'),date:dateKey(),name:s.name,status:'Present'});save('QR attendance marked',true);render()}
async function cameraQR(){if(!('BarcodeDetector' in window))return toast('Camera QR scanner not supported; type Student ID');try{const det=new BarcodeDetector({formats:['qr_code']}),v=document.createElement('video');v.setAttribute('playsinline','');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});v.srcObject=stream;await v.play();document.getElementById('qrstatus').appendChild(v);const loop=async()=>{try{const codes=await det.detect(v);if(codes[0]?.rawValue){stream.getTracks().forEach(t=>t.stop());qrvalue.value=codes[0].rawValue;qrMark();return}}catch(e){}requestAnimationFrame(loop)};loop()}catch(e){toast('Camera permission denied')}}
function notificationsPage(){return `<div class="panel"><input class="field" id="ntext" placeholder="Notification"><button class="primary-btn" onclick="addNotification()">ADD NOTIFICATION</button></div><div class="list-card">${db.notifications.map((n,i)=>`<div class="activity activity-with-action"><span>🔔 ${esc(n)}</span><button class="chip" onclick="deleteNotification(${i})">Delete</button></div>`).join('')||'<div class="activity">No notifications.</div>'}</div>`}
function addNotification(){if(!ntext.value.trim())return;db.notifications.unshift(ntext.value.trim());save('Notification added');render()}
function deleteNotification(i){db.notifications.splice(i,1);save('Notification deleted');render()}
function messagesQuick(){go('messages')}
function callStudent(id){const s=db.students.find(x=>x.id===id);if(!s?.phone)return toast('Mobile not available');window.location.href='tel:'+String(s.phone).replace(/[^0-9+]/g,'')}
function whatsappStudent(id){const s=db.students.find(x=>x.id===id);if(!s?.phone)return toast('Mobile not available');openWhatsApp(s.phone,`Hello ${s.parent||s.name}, this is ${db.settings.academy}.`)}
function motivationalPage(){return `<div class="panel"><h3>🌟 Motivational Posts</h3><input class="field" id="motext" placeholder="Write a motivational post"><button class="primary-btn" onclick="addMotivation()">ADD POST</button></div><div class="list-card">${db.motivationalPosts.map(x=>`<div class="activity activity-with-action"><span>${esc(x.text)}<br><small>${esc(x.date)}</small></span><button class="chip" onclick="deleteMotivation('${esc(x.id)}')">Delete</button></div>`).join('')||'<div class="activity">No posts.</div>'}</div>`}
function addMotivation(){if(!motext.value.trim())return;db.motivationalPosts.unshift({id:makeId('MOT'),text:motext.value.trim(),date:dateKey()});save('Motivational post added');render()}
function deleteMotivation(id){db.motivationalPosts=db.motivationalPosts.filter(x=>x.id!==id);save('Post deleted');render()}
function morePage(){const modules=[['🏫','Batches','batches'],['📝','Exams','exams'],['📈','Performance','performance'],['💵','Income','income'],['💸','Expenses','expenses'],['📩','Enquiries','enquiries'],['👨‍🏫','Staff','staff'],['📊','Reports','reports'],['🔔','Notifications','notifications'],['☑️','To-Do Tasks','todo'],['🖥️','Online Exams','online'],['📢','Broadcast & Messages','messages'],['📷','QR Attendance','qr'],['🌟','Motivational Posts','motivational'],['☁️','Backup & Restore','backup'],['⚙️','Settings','settings']];return `<div class="module-grid">${modules.map(m=>`<button class="module-card" onclick="go('${m[2]}')"><span class="ico">${m[0]}</span><strong>${m[1]}</strong><small>Open module</small></button>`).join('')}</div><button class="danger" onclick="logout()">↪ LOG OUT</button>`}
function settingsPage(){const connected=!!window.EVFirebase?.auth?.currentUser;return `<div class="panel"><h3>⚙️ System Settings</h3><label>Academy Name</label><input class="field" id="setacademy" value="${esc(db.settings.academy)}"><label>Address</label><input class="field" id="setaddress" value="${esc(db.settings.address)}"><label>Phone</label><input class="field" id="setphone" value="${esc(db.settings.phone)}"><label>Authorized Signature</label><input class="field" id="setsign" value="${esc(db.settings.signature)}"><label>Date Format</label><select class="field" id="setdate"><option ${db.settings.dateFormat==='DD/MM/YYYY'?'selected':''}>DD/MM/YYYY</option><option ${db.settings.dateFormat==='MM/DD/YYYY'?'selected':''}>MM/DD/YYYY</option><option ${db.settings.dateFormat==='YYYY-MM-DD'?'selected':''}>YYYY-MM-DD</option></select><button class="primary-btn" onclick="saveSettings()">SAVE SETTINGS</button></div><div class="panel">${kv('Account',db.user?.login||'—')}${kv('Role',db.user?.role||'Admin')}${kv('Firebase',connected?'Connected ✓':'Offline')}</div><button class="secondary-btn" onclick="resetData()">RESET MY DATA</button>`}
function saveSettings(){db.settings={...db.settings,academy:setacademy.value.trim()||db.settings.academy,address:setaddress.value.trim(),phone:setphone.value.trim(),signature:setsign.value.trim(),dateFormat:setdate.value};save('Settings saved',true);render()}
function backupPage(){return `<div class="panel"><h3>☁️ Backup & Restore</h3><p class="muted">Local JSON backup + cloud synced data.</p><button class="primary-btn" onclick="downloadBackup()">DOWNLOAD JSON BACKUP</button><label class="secondary-btn file-btn">RESTORE JSON BACKUP<input type="file" accept="application/json,.json" onchange="restoreBackup(event)" hidden></label><button class="secondary-btn" onclick="cloudSync()">☁️ SYNC NOW</button><button class="secondary-btn" onclick="exportExcel(reportRows('students'),'students-backup.xls')">EXCEL STUDENT BACKUP</button></div>`}
function downloadBackup(){downloadFile('ezee-vision-backup.json',JSON.stringify(db,null,2),'application/json');toast('Backup downloaded')}
function restoreBackup(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=normalize(JSON.parse(r.result));db.user={...db.user,uid:window.EVFirebase.auth.currentUser.uid};save('Backup restored',true);render()}catch(x){toast('Invalid backup')}};r.readAsText(f)}
function cloudSync(){save('Cloud synced',true)}
async function resetData(){if(!confirm('Reset all coaching data?'))return;const u=db.user;db=clone(DEFAULT_DB);db.user=u;save('Data reset',true);render()}
function downloadFile(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function openWhatsApp(phone,text){const p=String(phone).replace(/\D/g,'');if(!p)return toast('Invalid mobile');window.open(`https://wa.me/${p.length===10?'91'+p:p}?text=${encodeURIComponent(text)}`,'_blank')}
function batchReport(id){const b=db.batches.find(x=>x.id===id);if(!b)return;const rows=reportRows('students').filter(r=>r.Batch===b.name);printWindow('Batch Report',`<h2>${esc(b.name)}</h2>${tableHtml(rows)}`);exportCsvRows(rows,`${b.name.replace(/\s+/g,'-')}-report.csv`)}
window.addEventListener('DOMContentLoaded',init);
